### ISSUE TITLE
Changes in /live/track/get/clips/name

### ISSUE THREAD

**Issue by rimasinc** [ideoforms/AbletonOSC#37]
I started using AbletonOSC from version before date 2022-12-17.

Taking as an example track 0 (with empty clips), with this new version, the message `/live/track/get/clips/name` is returning:

`[0, null, null, null, null, null, null, null, null]`

In the previous version, the same message returned:

`[null, null, null, null, null, null, null, null, null]`

PS: I'm using the Open Stage Control server app

**Comment by ideoforms** [comment]
Apologies @rimasinc, this is a breaking change in the latest version:

All APIs that query track and clip information now reply with the *track and/or clip ID included in the responses*.
This is so that (a) it is possible to disambiguate between resposnes if the client simultaneously sends requests querying information for multiple tracks, and (b) so that the response signatures for "/live/track/start_listen" and "/live/track/get" are identical. 

I have added a note about this in the top of the README. 
To handle the new response, you can simply ignore the first (track_index) item in the OSC response.

Heads up that there may be one or two other breaking changes forthcoming as AbletonOSC is still in alpha development mode. I'm trying to get all of the APIs spot on, ahead of the first "proper" v1 release.

**Comment by rimasinc** [comment]
Got it. I will wait for the new updates. In the meantime, I'll stick with the previous version. For me the separation of information by objects (track one thing, clip another) flows better. Thanks for listening!
