### ISSUE TITLE
Request: Let new listener trigger a 'get'

### ISSUE THREAD

**Issue by Coupe70** [ideoforms/AbletonOSC#40]
At the moment listeners only send information when a change occurs.
So to get the actual state of something in the beginning you have to manually query it before starting a listener.

Would it be possible to let a new listener do this automatically when it is started?

Example:
**/live/track/start_listen/color (track_id)** would automatically trigger a **/live/track/get/color (track_id)** once.

This would automatically update a control when a listener is started and do no harm if it is already up-to-date for some reason.

**Comment by rimasinc** [comment]
I like this idea. I'm trying to figure out a way to receive messages when Live is opened based on the current AbletonOSC files.

In addition to the application.py file (which sends self.osc_server.send("/live/startup" every time Live is started) I discovered, for example, that in the song.py file it is also possible to send start messages (and they work in parts).

In the song.py files, I tried putting the following message on line 131:
self.osc_server.send("/live/track/get/clips/name", [0])

With this message, when starting an empty live set or opening a live set from a previously saved project (with existing clips) the initial result is just the normal index of the widget I'm using in the Open Stage Control app, which returns the result 0 , 1, 2, 3 (I'm using a matrix widget to get the name of the first 4 clips on track 0)

To get the clip names, I created the GET CLIP NAMES button in my layout to send the message send("127.0.0.1:11000", "/live/track/get/clips/name", [0]). When I press this button, if the live set is empty, it will return (0, null, null, null, null)... If the set has previously saved clips, or if I record new clips, the names will appear correctly only after I press the GET CLIP NAMES button.

If after pressing GET CLIP NAMES I open a new blank set (or when opening another saved project containing clips) the result in the widget "updates" to 0, 1, 2, 3.

So the message sent through the song.py file works by changing the message content, but partially. The problem is that, when opening or restarting a live set, the message self.osc_server.send("/live/track/get/clips/name", [0]) does not return the clip names (you need to trigger a button with this message)
 
I tried on line 132 the same procedures for the message
self.osc_server.send("/live/song/start_listener/tempo") this time using a text widget. The result is the same.

I'm very green in python (a toddler crawling) but, I think an alternative would be a file, perhaps named osc_init.py containing the necessary loops for the refresh state of elements that make sense for opening (or restarting) messages of a live set.

**Comment by Coupe70** [comment]
Hm, this not really what my request is about...

**Comment by ideoforms** [comment]
I think this is a good idea -  will implement

**Comment by ideoforms** [comment]
Done!

**Comment by Coupe70** [comment]
Checked with
**/live/track/start_listen/color**, **/live/track/start_listen/name** and the new **/live/track/start_listen/***
Works and is a really cool to omit the initial **get** before starting listeners!
