### ISSUE TITLE
AbletonOSC only seems to listen to Localhost?

### ISSUE THREAD

**Issue by J-Bon1** [ideoforms/AbletonOSC#41]
Hoi,

I have been using AbletonOSC (receiver) and Unity3D (sender) for half a year on a single pc without any problems, always sending to localhost (127.0.0.1). I am trying to split the OSC sender software (Unity3D application) and Ableton to two different PCs in a network, but AbletonOSC does not pick up the messages. With a 3rd software (Wireshark) I have been monitoring the incoming network traffic on the Ableton PC and the OSC messages arrive on the correct port but don't get picked up by AbletonOSC. Is there any way to have the plugin listen to other IPs than localhost or am I doing something wrong? 

Any help is greatly appreciated. Thanks a lot for that awesome plugin btw! 

Greetings,
JM

**Comment by ideoforms** [comment]
Could you clone the latest commit and confirm that the problem is still happening? Until a fairly recent version, the script did specifically bind to 127.0.0.1. However, I fixed this a while back (November 11th) such that it should now listen on all network interfaces (0.0.0.0). If this is still happening, let me know with screenshots of the Wireshark captures, and I'll have a think.

**Comment by J-Bon1** [comment]
Ah, it works on the newer version. Thanks for the quick reply. Apologies, my fault, I did not realize I there was a newer version released where this got fixed.

**Comment by ideoforms** [comment]
Great, glad it worked! 
I'd love to hear what you're doing with it if you're happy to share any info - https://erase.net/contact
