### ISSUE TITLE
Request: add instrument to track

### ISSUE THREAD

**Issue by Audiophil83** [ideoforms/AbletonOSC#53]
I am writing a Python Cli tool that lets me select a few chords and sends them to Live using AbletonOSC. It works fine but the more I think about this the more I want this to become a kind of template creator where I can quickly create jam tracks specifying only the chord progression. 

So my question, is there a way to add instruments to tracks using AbletonOSC. I tried many things, but I guess it is not yet implemented. Is this something that is planned to come?

btw I really appreciate this project, thanks for the good work!

**Comment by ideoforms** [comment]
Thanks for the feedback! Adding instruments is not yet supported; I am keen to introduce this at some point in the next few months, but this is very much a passion project and my time availability is limited.

BTW, as you're using Python to develop your client, you might also be interested in [pylive](https://github.com/ideoforms/pylive/tree/feature/abletonosc), a Python library that encapsulates common functionality so that you don't need to hand-craft OSC messages to interact with AbletonOSC. This is lagging a bit behind, but will shortly (by ~late Feb) be updated to work with all of the latest AbletonOSC functionality.

**Comment by Audiophil83** [comment]
Thanks for this info. I am glad to hear this is coming. Thank you also for pointing out pylive. I have seen it but did not use it yet. You are right it is a much cleaner way of doing things. I will look into it.
